### ISSUE TITLE
`Z Stepper Motor` intersects `Leadscrew_mount_back_001`

### ISSUE THREAD

**Issue by lucian151** [magpie-printer/magpie#2]
This collision between the Leadscrew_mount_back_001 and motor needs to be addressed:
<img width="676" alt="Screenshot 2024-10-06 at 6 21 55 PM" src="https://github.com/user-attachments/assets/c9829a17-7b9c-4093-a5ee-b2f0e7d836ef">

**Comment by owenwvaughn** [comment]
![collision_fix](https://github.com/user-attachments/assets/792c4e5f-ebbe-4cc8-9c98-5edcb64a7c53)
